### ISSUE TITLE
GDB Support

### ISSUE THREAD

**Issue by rellermeyer** [rellermeyer/course_os#11]
Put initial GDB support in place so that the running kernel can be debugged (in a meaningful way) through GDB attached to the running QEMU instance.

**Comment by NULLx76** [comment]
#45 will also add support for debugging through qemu.

**Comment by jonay2000** [comment]
And from within Clion :)

**Comment by NULLx76** [comment]
Not just CLion, most IDEs that have remote debugging functionality should work.

**Comment by NULLx76** [comment]
Resolved by #45
