### ISSUE TITLE
Test Framework

### ISSUE THREAD

**Issue by rellermeyer** [rellermeyer/course_os#20]
We could need a way to run tests from within the running kernel to ensure correctness and avoid regression. 
Once we have this people implementing new functionality could provide corresponding test cases written in this framework.

**Comment by collinc777** [comment]
did this end up being implemented??

**Comment by lkolbly** [comment]
A little bit. It appears that in the master branch the kernel/test.c file has some sort of test framework, which references some tests in the kernel/tests/. It would be certainly be worth documenting the framework and figuring out what's there, if you want to do that (I'm not aware of any other test framework in the kernel).

**Comment by jonay2000** [comment]
closing because it's implemented well now :
)
