### ISSUE TITLE
Power Management

### ISSUE THREAD

**Issue by rellermeyer** [rellermeyer/course_os#23]
We possibly want some initial power management sending the CPU into low power states if idle, etc. 
Some thoughts on what is involved can be found here: http://www.linaro.org/documents/download/84a5990d6f227c90e3d3a3ad2af0e22c4fd1d0bd4a6c7

**Comment by c4k9c0** [comment]
To what degree was this completed last semester? If not fully done this seems like something interesting to work on.

**Comment by lkolbly** [comment]
Take a peek at the power_management branch. It may have been merged, but that's what's there.

**Comment by rellermeyer** [comment]
Most of the work is still to be done. We don't have a real scheduler yet and only few device drivers so you can imagine how much more opportunity there is.
