### ISSUE TITLE
[Urgent] I accidentally messed up the master when resetting my branch

### ISSUE THREAD

**Issue by bluejamesbond** [rellermeyer/course_os#32]
PLEASE do not push or make any changes. If someone can revert back all the changes, it would be much appreciated. I have contacted Lane already. Let's hope this can be brought back. I apologize for all the issues.

**Comment by bluejamesbond** [comment]
Okay I have fixed it. Ill be more careful from now on (but that was scary).

**Comment by lkolbly** [comment]
Glad to hear it all worked out. But interestingly you're not the only person to have had this issue last night, I know of one other person who did.
